io_frequency_caps:
  adults:
  - 20 per 1 Month
  - 1 per 30 Minutes
  kids:
  - 1 per 15 Minutes
ad_units:
  pplus_cbs_pluto_vcbs:
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
  mtve_bet_vh1:
  - Viacom_Promo_Pre_Roll
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
  nick:
  - Viacom_NickJR_Promo_Pre_Roll
  - ViacomCBS_Kids_Promo_Mid_Roll
  - ViacomCBS_Kids_Promo_Pre_Roll
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
  pause_ads:
  - Pause_Ad
  premium_preroll:
  - PPlus_Commercial Free_Promo
  - PPlus_LinearSkippable_Promo_Pre_Roll_1s
  essential_bumper:
  - CBS_Brand Bumper_Mid_Roll_Last
  cbs_house_all:
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
  cbs_house_mid_post:
  - Paramount House Midroll
  - Paramount House Postroll
  cbs_preroll:
  - CBS_Promo_Pre_Roll
  cbs_after_midroll_bumper:
  - CBS_Brand Bumper_Mid_Roll_Last
  cbs_1z_lockdown:
  - Mid_Roll_Break 1_Last
  cbs_2z_lockdown:
  - Mid_Roll_Break 2_Last
  viacom_promo:
  - Viacom_Promo_Pre_Roll
  - Paramount House Midroll
  - Paramount House Postroll
  pluto_video_domination:
  - Paramount House Preroll
  - Paramount House Midroll
  pplus_uk_house:
  - Pplus_INTL_Promo_Pre_Roll
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
  network_10_house:
  - Net10_Live_ Pre_Roll
  - Paramount House Preroll
  - Paramount House Midroll
  - Paramount House Postroll
format_ad_unit_group:
  remnant_video: pplus_cbs_pluto_vcbs
  pause_ads: pause_ads
  premium_preroll: premium_preroll
  essential_bumper: essential_bumper
  cbs_preroll: cbs_preroll
  cbs_after_midroll_bumper: cbs_after_midroll_bumper
  cbs_1z_lockdown: cbs_1z_lockdown
  cbs_2z_lockdown: cbs_2z_lockdown
  mtve_after_midroll_bumper: cbs_after_midroll_bumper
  bet_after_midroll_bumper: cbs_after_midroll_bumper
  pluto_video_domination: pluto_video_domination
  pluto_es_remnant: pplus_cbs_pluto_vcbs
  pplus_kids_remnant: pplus_cbs_pluto_vcbs
  pplus_kids_premium_preroll: premium_preroll
  pplus_kids_essential_bumper: essential_bumper
  pplus_kids_remnant_pplus: pplus_uk_house
  pplus_kids_remnant_pluto: pplus_cbs_pluto_vcbs
  pplus_uk_remnant_pplus: pplus_uk_house
  pplus_uk_remnant_pluto: pplus_cbs_pluto_vcbs
  pluto_ca_remnant: pplus_cbs_pluto_vcbs
  network_10_remnant: network_10_house
