network_id: 520311
brands:
  paramount_plus_domestic:
    display_name: Paramount+ Domestic
    advertiser_name_contains:
    - VCBS
    - Paramount
    template_campaign_id: '86543608'
    template_io_id: '92725144'
    campaign_name: Paramount + - USA
    ad_unit_groups:
      remnant_video: pplus_cbs_pluto_vcbs
      pause_ads: pause_ads
      premium_preroll: premium_preroll
      essential_bumper: essential_bumper
    formats:
    - remnant_video
    - pause_ads
    - premium_preroll
    - essential_bumper
  cbs_sports:
    display_name: CBS Sports
    advertiser_name_contains:
    - VCBS
    - CBS
    template_campaign_id: '54413703'
    template_io_id: '91459093'
    campaign_name: CBS Sports - USA
    ad_unit_groups:
      remnant_video: cbs_house_all
    extra_exclude_video_groups:
    - '73409791'
    formats:
    - remnant_video
  cbs_news:
    display_name: CBS News
    advertiser_name_contains:
    - VCBS
    - CBS
    template_campaign_id: '54413662'
    template_io_id: '94971594'
    campaign_name: CBS News - USA
    ad_unit_groups:
      remnant_video: cbs_house_mid_post
    extra_exclude_site_groups:
    - '1037683'
    - '1038397'
    - '1038398'
    - '1038399'
    - '1038400'
    formats:
    - remnant_video
  cbs_network:
    display_name: CBS Network
    advertiser_name_contains:
    - VCBS
    - CBS
    template_campaign_id: '54407793'
    template_io_id: '93984940'
    campaign_name: CBS Network - USA
    ad_unit_groups:
      remnant_video: cbs_house_all
      pause_ads: pause_ads
      cbs_preroll: cbs_preroll
      cbs_after_midroll_bumper: cbs_after_midroll_bumper
      cbs_1z_lockdown: cbs_1z_lockdown
      cbs_2z_lockdown: cbs_2z_lockdown
    formats:
    - remnant_video
    - pause_ads
    - cbs_preroll
    - cbs_after_midroll_bumper
    - cbs_1z_lockdown
    - cbs_2z_lockdown
  mtve:
    display_name: MTVE
    advertiser_name_contains:
    - VCBS
    - MTV
    template_campaign_id: '54413666'
    template_io_id: '59975938'
    campaign_name: MTVE - USA
    main_site_groups:
    - '929392'
    - '932592'
    - '932591'
    include_video_groups:
    - '73408899'
    extra_exclude_video_groups:
    - '73408858'
    - '73408859'
    ad_unit_groups:
      remnant_video: viacom_promo
      mtve_after_midroll_bumper: cbs_after_midroll_bumper
    formats:
    - remnant_video
    - mtve_after_midroll_bumper
  bet:
    display_name: BET
    advertiser_name_contains:
    - VCBS
    - BET
    template_campaign_id: '68562294'
    template_io_id: '94999325'
    campaign_name: BET Media Group - USA
    main_site_groups:
    - '1072587'
    include_video_groups:
    - '73408894'
    extra_exclude_video_groups:
    - '73408899'
    - '73408859'
    - '73408891'
    - '73408896'
    - '73408858'
    - '73408890'
    - '73408897'
    ad_unit_groups:
      remnant_video: viacom_promo
      bet_after_midroll_bumper: cbs_after_midroll_bumper
    formats:
    - remnant_video
    - bet_after_midroll_bumper
  pluto_tv:
    display_name: Pluto TV
    advertiser_name_contains:
    - VCBS
    - Pluto
    template_campaign_id: '54413718'
    template_io_id: '90867946'
    campaign_name: Pluto TV - USA
    main_site_groups:
    - '929392'
    extra_exclude_site_groups:
    - '932411'
    - '932412'
    ad_unit_groups:
      remnant_video: cbs_house_mid_post
      pluto_video_domination: pluto_video_domination
    formats:
    - remnant_video
  pluto_tv_xco:
    display_name: Pluto TV XCO
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '54413625'
    template_io_id: '95107045'
    campaign_name: Pluto TV (Cross-Company) - USA
    main_site_groups:
    - '932592'
    - '932591'
    extra_exclude_site_groups:
    - '929392'
    - '931759'
    ad_unit_groups:
      remnant_video: cbs_house_all
    formats:
    - remnant_video
  pluto_es_adult:
    display_name: Pluto TV - En Español
    advertiser_name_contains:
    - VCBS
    - Spanish
    template_campaign_id: '54439023'
    campaign_name: Pluto TV - En Espanol - USA
    formats:
    - pluto_es_remnant
    ad_unit_groups:
      pluto_es_remnant: pplus_cbs_pluto_vcbs
    placement_name_suffix: Spanish - USA
    relationship_sets:
    - set_name: Targeting VOD
      include:
      - video_group:
        - '75279406'
      - site_group:
        - '1120870'
        - '1253848'
      exclude:
        site_group:
        - '932270'
        - '932411'
        - '932412'
    - set_name: En Espanol
      include:
      - site_group:
        - '951392'
        - '1163091'
      exclude:
        site_group:
        - '932270'
        - '932411'
        - '932412'
  pluto_es_kids:
    display_name: Pluto TV - En Español - Kids
    advertiser_name_contains:
    - VCBS
    - Spanish
    template_campaign_id: '62081253'
    campaign_name: Pluto TV - Kids - En Espanol - USA
    formats:
    - pluto_es_remnant
    ad_unit_groups:
      pluto_es_remnant: pplus_cbs_pluto_vcbs
    placement_name_suffix: Kids
    relationship_sets:
    - set_name: Set One
      include:
      - site_group:
        - '929392'
      - site_group:
        - '932215'
      - video_group:
        - '73408862'
        - '86471529'
        site_group:
        - '932400'
      exclude:
        site_group:
        - '932411'
        - '932412'
    - set_name: Set Two
      include:
      - video_group:
        - '75279406'
      - video_group:
        - '73408862'
        - '73408864'
        - '86471529'
        site_group:
        - '932400'
      - site_group:
        - '929392'
      exclude:
        site_group:
        - '932411'
        - '932412'
        - '1237515'
    - set_name: Kids Channels
      include:
      - video_group:
        - '86471529'
        site_group:
        - '932400'
      - site_group:
        - '932063'
      exclude:
        site_group:
        - '932411'
        - '932412'
  paramount_plus_kids:
    display_name: Paramount+ Kids (USA)
    advertiser_name_contains:
    - VCBS
    - Kids
    template_campaign_id: '54440942'
    campaign_name: Paramount + - Kids - USA
    kids: true
    formats:
    - pplus_kids_remnant
    - pplus_kids_premium_preroll
    - pplus_kids_essential_bumper
    ad_unit_groups:
      pplus_kids_remnant: pplus_cbs_pluto_vcbs
      pplus_kids_premium_preroll: premium_preroll
      pplus_kids_essential_bumper: essential_bumper
  paramount_plus_kids_uk:
    display_name: Paramount+ Kids (UK)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '75617429'
    campaign_name: Paramount + - Kids - UK
    kids: true
    formats:
    - pplus_kids_remnant_pplus
    - pplus_kids_remnant_pluto
    - pplus_kids_premium_preroll
    - pplus_kids_essential_bumper
    ad_unit_groups:
      pplus_kids_remnant_pplus: pplus_uk_house
      pplus_kids_remnant_pluto: pplus_cbs_pluto_vcbs
      pplus_kids_premium_preroll: premium_preroll
      pplus_kids_essential_bumper: essential_bumper
    format_overrides:
      pplus_kids_essential_bumper:
        plan_label: Basic Plan
  pluto_tv_uk:
    display_name: Pluto TV (UK)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72286125'
    template_io_id: '87074612'
    campaign_name: Pluto TV - UK
    main_site_groups:
    - '929392'
    extra_exclude_site_groups:
    - '932411'
    - '932412'
    ad_unit_groups:
      remnant_video: pplus_cbs_pluto_vcbs
    formats:
    - remnant_video
  paramount_plus_uk:
    display_name: Paramount+ (UK)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '73711557'
    template_io_id: '81277963'
    campaign_name: Paramount + - UK
    formats:
    - pplus_uk_remnant_pplus
    - pause_ads
    - premium_preroll
    - essential_bumper
    ad_unit_groups:
      pplus_uk_remnant_pplus: pplus_uk_house
      pplus_uk_remnant_pluto: pplus_cbs_pluto_vcbs
      pause_ads: pause_ads
      premium_preroll: premium_preroll
      essential_bumper: essential_bumper
    format_overrides:
      essential_bumper:
        plan_label: Basic Plan
    optional_formats:
    - pplus_uk_remnant_pluto
  pluto_ca_en:
    display_name: Pluto TV - English (CA)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72285996'
    campaign_name: Pluto TV - English - CA
    main_site_groups:
    - '929392'
    formats:
    - remnant_video
    ad_unit_groups:
      remnant_video: pplus_cbs_pluto_vcbs
    format_overrides:
      remnant_video:
        drop_preroll_at_duration: 30
        drop_units:
        - Paramount House Preroll
  paramount_plus_ca:
    display_name: Paramount+ - English (CA)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72285992'
    campaign_name: Paramount + - English - CA
    main_site_groups:
    - '929392'
    - '932583'
    - '932591'
    - '932592'
    formats:
    - remnant_video
    - premium_preroll
    - essential_bumper
    ad_unit_groups:
      remnant_video: pplus_uk_house
      premium_preroll: premium_preroll
      essential_bumper: essential_bumper
    format_overrides:
      essential_bumper:
        plan_label: Basic Plan
      remnant_video:
        drop_preroll_at_duration: 30
        drop_units:
        - Paramount House Preroll
  paramount_plus_kids_ca:
    display_name: Paramount+ Kids (CA English)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72729853'
    campaign_name: Paramount + - Kids - English - CA
    kids: true
    formats:
    - pplus_kids_remnant
    - pplus_kids_premium_preroll
    - pplus_kids_essential_bumper
    ad_unit_groups:
      pplus_kids_remnant: pplus_cbs_pluto_vcbs
      pplus_kids_premium_preroll: premium_preroll
      pplus_kids_essential_bumper: essential_bumper
    format_overrides:
      pplus_kids_remnant:
        duration_infix: ''
  pluto_ca_kids_en:
    display_name: Pluto TV - Kids - English (CA)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72722746'
    campaign_name: Pluto TV - Kids - English - CA
    kids: true
    formats:
    - pplus_kids_remnant
    ad_unit_groups:
      pplus_kids_remnant: pplus_cbs_pluto_vcbs
    format_overrides:
      pplus_kids_remnant:
        kids_main_site_groups:
        - '929392'
        duration_infix: ''
  nick_ca_en:
    display_name: Nick - Kids - English (CA)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '86542904'
    campaign_name: Nick - Kids - English - CA
    kids: true
    formats:
    - pplus_kids_remnant
    ad_unit_groups:
      pplus_kids_remnant: pplus_cbs_pluto_vcbs
    format_overrides:
      pplus_kids_remnant:
        kids_main_site_groups:
        - '929392'
        duration_infix: (Pluto)
  pluto_ca_fr:
    display_name: Pluto TV - French (CA)
    advertiser_name_contains:
    - VCBS
    template_campaign_id: '72302590'
    campaign_name: Pluto TV - French - CA
    main_site_groups:
    - '929392'
    formats:
    - pluto_es_remnant
    ad_unit_groups:
      pluto_es_remnant: pplus_cbs_pluto_vcbs
    placement_name_suffix: French - CA
