domestic_usa:
  main_site_groups:
  - '929392'
  - '932583'
  - '932591'
  - '932592'
  pplus_site_group:
  - '932583'
  exclude_site_groups: []
  exclude_video_groups:
  - '73410101'
  recommended_show_key: recommended_show
  recommended_show_placeholder: TBD
  pause:
    main_site_groups:
    - '929392'
    - '932583'
    - '932592'
    platform_site_groups:
    - '929447'
    - '929449'
    exclude_key_values:
    - sb=14
    - tsb=14
    - tve=14
    - tve=17
    exclude_video_groups:
    - '98314060'
    - '98405426'
    - '311826361'
kids:
  base_video_group: '86471529'
  older_video_group: '73408862'
  younger_video_group: '73408864'
  content_site_group: '932400'
us_pluto_dnr:
  site_group: '951172'
  except_brands:
  - pluto_tv
